<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Services', 'photology' ),
	'categories' => array( 'photology-core' ),
	'content'    => '<!-- wp:gutenverse/section {"elementId":"guten-aM1B5R","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10","top":"80","bottom":"80"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40"}}}} -->
<div class="section-wrapper" data-id="aM1B5R"><section class="wp-block-gutenverse-section guten-element guten-section guten-aM1B5R layout-boxed align-stretch"><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-DYjRwA"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-DYjRwA"><div class="guten-column-wrapper" data-id="DYjRwA"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-zQgZ3t","verticalAlign":"center","margin":{"Desktop":{"unit":"px","dimension":{"top":""}}},"padding":{"Desktop":[]}} -->
<div class="section-wrapper" data-id="zQgZ3t"><section class="wp-block-gutenverse-section guten-element guten-section guten-zQgZ3t layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50},"sectionVerticalAlign":"center","elementId":"guten-9aGyS1"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-9aGyS1"><div class="guten-column-wrapper" data-id="9aGyS1"><!-- wp:gutenverse/heading {"elementId":"guten-G251P8","color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"h2-font","font":{"label":"Prata","value":"Prata","type":"google"},"size":{"Desktop":{"unit":"px","point":"38"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-G251P8 animated guten-element-hide desktop-fadeInLeft">What We Offer</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-gUmaFf","color":{"type":"variable","id":"theme-7"},"typography":{"type":"variable","id":"accent-big-font","font":{"label":"Prata","value":"Prata","type":"google"},"size":{"Desktop":{"unit":"px","point":"140"},"Tablet":{"unit":"px","point":"80"},"Mobile":{"unit":"px","point":"40"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"transform":"uppercase","spacing":{"Desktop":"0.1"},"weight":"600"},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"zIndex":{"Desktop":"-1"},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"100"},"positioningType":{"Desktop":"inline"},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"unit":"%","point":""}},"positioningTop":{"Desktop":{"unit":"%","point":"-21"},"Mobile":{"point":"-19","unit":"px"}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-gUmaFf animated guten-element-hide desktop-fadeInRight">Services</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-rbVW8W","alignment":{"Desktop":"left"},"textColor":{"type":"variable","id":"theme-4"},"typography":{"type":"variable","id":"bodytext-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"}} -->
<div class="guten-element gutenverse-text-editor guten-rbVW8W animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ut enim ad minim veniam</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"sectionVerticalAlign":"center","elementId":"guten-96t9ES","hideMobile":true} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-96t9ES hide-mobile"><div class="guten-column-wrapper" data-id="96t9ES"></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-NFq5v4","margin":{"Desktop":{"unit":"px","dimension":{"top":"40"}}},"padding":{"Desktop":[]}} -->
<div class="section-wrapper" data-id="NFq5v4"><section class="wp-block-gutenverse-section guten-element guten-section guten-NFq5v4 layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Mobile":null},"elementId":"guten-sK63qf","margin":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-sK63qf"><div class="guten-column-wrapper" data-id="sK63qf"><!-- wp:gutenverse/icon-box {"elementId":"guten-pjWA0f","separateButtonLink":false,"title":"Wedding Photography","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore dolore magna aliqua","icon":"gtn gtn-rings-light","align":{"Desktop":"left"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":[],"Mobile":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":[]},"iconColor":{"type":"variable","id":"theme-2"},"iconBorder":{"radius":{"Desktop":[],"Mobile":[]}},"iconBorderHover":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":[],"Mobile":[]},"titleMargin":{"Desktop":[],"Mobile":[]},"titleColor":{"type":"variable","id":"theme-0"},"titleTypography":{"type":"variable","id":"h3-alt-font","font":{"label":"Prata","value":"Prata","type":"google"},"size":{"Desktop":{"unit":"px","point":"20"},"Mobile":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400"},"descMargin":{"Desktop":[],"Mobile":[]},"descColor":{"type":"variable","id":"theme-4"},"descTypography":{"type":"variable","id":"bodytext-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"},"parentSelector":".guten-pjWA0f:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-pjWA0f animated guten-element-hide desktop-fadeInLeft guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-rings-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Wedding Photography</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore dolore magna aliqua</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Mobile":null},"elementId":"guten-Asgn3h","margin":{"Desktop":{"unit":"px","dimension":{"left":"10","right":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-Asgn3h"><div class="guten-column-wrapper" data-id="Asgn3h"><!-- wp:gutenverse/icon-box {"elementId":"guten-Sop1ba","separateButtonLink":false,"title":"Event Photography","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore dolore magna aliqua","icon":"gtn gtn-photo-camera1-light","align":{"Desktop":"left"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":[],"Mobile":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"iconColor":{"type":"variable","id":"theme-2"},"iconBorder":{"radius":{"Desktop":[],"Mobile":[]}},"titlePadding":{"Desktop":[],"Mobile":[]},"titleMargin":{"Desktop":[],"Mobile":[]},"titleColor":{"type":"variable","id":"theme-0"},"titleTypography":{"type":"variable","id":"h3-alt-font","font":{"label":"Prata","value":"Prata","type":"google"},"size":{"Desktop":{"unit":"px","point":"20"},"Mobile":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400"},"descMargin":{"Desktop":[],"Mobile":[]},"descColor":{"type":"variable","id":"theme-4"},"descTypography":{"type":"variable","id":"bodytext-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"400"},"parentSelector":".guten-Sop1ba:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-Sop1ba animated guten-element-hide desktop-fadeInLeft guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-photo-camera1-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Event Photography</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore dolore magna aliqua</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Mobile":null},"elementId":"guten-khzL6C","margin":{"Desktop":{"unit":"px","dimension":{"left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-khzL6C"><div class="guten-column-wrapper" data-id="khzL6C"><!-- wp:gutenverse/icon-box {"elementId":"guten-BQktXE","separateButtonLink":false,"title":"Business Photography","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore dolore magna aliqua","icon":"gtn gtn-briefcase1-light","align":{"Desktop":"left"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":[],"Mobile":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"iconColor":{"type":"variable","id":"theme-2"},"iconBorder":{"radius":{"Desktop":[],"Mobile":[]}},"iconBorderHover":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":[],"Mobile":[]},"titleMargin":{"Desktop":[],"Mobile":[]},"titleColor":{"type":"variable","id":"theme-0"},"titleTypography":{"type":"variable","id":"h3-alt-font","font":{"label":"Prata","value":"Prata","type":"google"},"size":{"Desktop":{"unit":"px","point":"20"},"Mobile":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400"},"descMargin":{"Desktop":[],"Mobile":[]},"descColor":{"type":"variable","id":"theme-4"},"descTypography":{"type":"variable","id":"bodytext-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"600"},"parentSelector":".guten-BQktXE:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-BQktXE animated guten-element-hide desktop-fadeInLeft guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-briefcase1-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Business Photography</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore dolore magna aliqua</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/button {"elementId":"guten-tWtWoU","content":"All Service","alignButton":{"Desktop":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"theme-2"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"theme-0"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"","bottom":"","left":""}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"},"color":{"type":"variable","id":"theme-1"},"typography":{"type":"variable","id":"button-2-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"12"},"Mobile":{"unit":"px","point":"10"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"spacing":{"Desktop":"0.2"},"transform":"uppercase","weight":"400"},"hoverTextColor":{"type":"variable","id":"theme-1"}} -->
<div class="guten-element guten-button-wrapper guten-tWtWoU"><a class="guten-button animated guten-element-hide desktop-fadeInLeft guten-button-sm" href="#"><span>All Service</span></a></div>
<!-- /wp:gutenverse/button --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
