<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse About', 'photology' ),
	'categories' => array( 'photology-core' ),
	'content'    => '<!-- wp:gutenverse/section {"gap":"no","elementId":"guten-5e9nnt","verticalAlign":"center","background":{"type":"default","color":"","videoPlayOnMobile":false},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"left":"10","right":"10","top":"80","bottom":"80"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40","left":"10","right":"10"}}}} -->
<div class="section-wrapper" data-id="5e9nnt"><section class="wp-block-gutenverse-section guten-element guten-section guten-5e9nnt layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":48.6,"Tablet":100},"sectionVerticalAlign":"center","elementId":"guten-LLkRjW","background":{"type":"default","image":{"Desktop":{"id":15,"image":"' . esc_url( PHOTOLOGY_URI ) . 'assets/img/man-person-camera-photography-photographer-male-81765-pxhere.com.jpg"}},"position":{"Desktop":"center center"},"size":{"Desktop":"cover"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"100"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-LLkRjW animated guten-element-hide desktop-fadeInLeft"><div class="guten-column-wrapper" data-id="LLkRjW"><!-- wp:gutenverse/spacer {"elementId":"guten-de8ef1","space":{"Desktop":{"unit":"px","point":"520"},"Mobile":{"point":"315","unit":"px"},"Tablet":{"point":"","unit":"px"}},"border":{"radius":{"Desktop":[]}}} -->
<div class="guten-element guten-spacer guten-de8ef1"></div>
<!-- /wp:gutenverse/spacer --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":51.4,"Tablet":100,"Mobile":null},"sectionVerticalAlign":"center","elementId":"guten-hm22ZI","margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"60"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"10","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"left":"","top":"20","right":"","bottom":""}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-hm22ZI"><div class="guten-column-wrapper" data-id="hm22ZI"><!-- wp:gutenverse/heading {"elementId":"guten-2W1hqH","color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"h2-font","font":{"label":"Prata","value":"Prata","type":"google"},"size":{"Desktop":{"unit":"px","point":"38"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400"},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-2W1hqH animated guten-element-hide desktop-fadeInRight">Welcome To Photology</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-VP1Pdh","color":{"type":"variable","id":"theme-7"},"typography":{"type":"variable","id":"accent-big-font","font":{"label":"Prata","value":"Prata","type":"google"},"size":{"Desktop":{"unit":"px","point":"140"},"Tablet":{"unit":"px","point":"80"},"Mobile":{"unit":"px","point":"40"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"transform":"uppercase","spacing":{"Desktop":"0.1"},"weight":"600"},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"zIndex":{"Desktop":"-1"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"100"},"positioningType":{"Desktop":"inline"},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"unit":"%","point":""}},"positioningTop":{"Desktop":{"unit":"%","point":"-11"},"Tablet":{"point":"-20","unit":"px"},"Mobile":{"point":"-17","unit":"px"}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-VP1Pdh animated guten-element-hide desktop-fadeInLeft">About</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-wb6sWe","textColor":{"type":"variable","id":"theme-4"},"typography":{"type":"variable","id":"bodytext-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"200"}} -->
<div class="guten-element gutenverse-text-editor guten-wb6sWe animated guten-element-hide desktop-fadeInRight"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris </p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-1SUHJi","background":{"type":"default","color":{"type":"variable","id":"theme-7"},"videoPlayOnMobile":false},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"left":{"type":"solid","color":{"type":"variable","id":"theme-3"},"width":"5"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}},"Mobile":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"60","bottom":"20","left":"30"}},"Mobile":{"unit":"px","dimension":{"right":"20"}},"Tablet":{"unit":"px","dimension":{"top":"40","bottom":"40"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"400"}} -->
<div class="section-wrapper" data-id="1SUHJi"><section class="wp-block-gutenverse-section guten-element guten-section guten-1SUHJi animated guten-element-hide desktop-fadeInRight layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-hllSXT","verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"default","Tablet":"default","Mobile":"default"},"margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-hllSXT"><div class="guten-column-wrapper" data-id="hllSXT"><!-- wp:gutenverse/text-editor {"elementId":"guten-BEjv11","textColor":{"type":"variable","id":"theme-4"},"typography":{"type":"variable","id":"italic-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"style":"italic","weight":"300"},"margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":[],"Mobile":[]},"zIndex":{"Desktop":"2"}} -->
<div class="guten-element gutenverse-text-editor guten-BEjv11"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Photography is a way of feeling, of touching, of loving. What you have caught on film is captured forever. It remembers little things, long after you have forgotten everything</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/icon {"elementId":"guten-GLgqvo","icon":"gtn gtn-quote-light","iconColorOne":{"r":255,"g":255,"b":255,"a":0.01},"iconSize":{"Desktop":{"point":"100","unit":"px"},"Mobile":{"point":"85","unit":"px"},"Tablet":{"point":"","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconColorTwo":{"type":"variable","id":"theme-12"},"iconShape":"custom","border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]},"zIndex":{"Desktop":"0"},"positioningType":{"Desktop":"inline","Mobile":"inline"},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"unit":"%","point":""},"Mobile":{"point":"","unit":"px"}},"positioningRight":{"Desktop":{"point":"-40","unit":"px"},"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"-10","unit":"px"}},"positioningTop":{"Desktop":{"unit":"%","point":""},"Tablet":{"point":"","unit":"px"},"Mobile":{"unit":"%","point":""}},"positioningBottom":{"Tablet":{"point":"","unit":"px"}}} -->
<div class="wp-block-gutenverse-icon guten-element guten-GLgqvo guten-icon"><span class="guten-icon-wrapper custom stacked"><i class="gtn gtn-quote-light"></i></span></div>
<!-- /wp:gutenverse/icon --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/progress-bar {"elementId":"guten-hbCx04","title":"Photography","percentage":92,"barColor":{"type":"variable","id":"theme-12"},"trackColor":{"type":"variable","id":"theme-2"},"trackHeight":{"Desktop":"10"},"barRadius":{"Desktop":[],"Mobile":[]},"trackRadius":{"Desktop":[],"Mobile":[]},"barPadding":{"Desktop":[],"Mobile":[]},"barMargin":{"Desktop":[],"Mobile":[]},"titleColor":{"type":"variable","id":"theme-0"},"titleTypography":{"type":"variable","id":"h6-font","font":{"label":"Prata","value":"Prata","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"400"},"percentColor":{"type":"variable","id":"theme-4"},"percentTypography":{"type":"variable","id":"bodytext-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-progress-bar guten-hbCx04"><div class="progress-group"><div class="progress-skill-bar"><div class="skill-bar-content"><span class="skill-title">Photography</span></div><div class="skill-bar"><div class="skill-track" data-width="92" data-duration="3500"><div class="number-percentage-wrapper"><span class="number-percentage loaded"></span></div></div></div></div></div></div>
<!-- /wp:gutenverse/progress-bar -->

<!-- wp:gutenverse/progress-bar {"elementId":"guten-T9T8GR","title":"Videography","percentage":89,"barColor":{"type":"variable","id":"theme-12"},"trackColor":{"type":"variable","id":"theme-2"},"trackHeight":{"Desktop":"10"},"barRadius":{"Desktop":[],"Mobile":[]},"trackRadius":{"Desktop":[],"Mobile":[]},"barPadding":{"Desktop":[],"Mobile":[]},"barMargin":{"Desktop":[],"Mobile":[]},"titleColor":{"type":"variable","id":"theme-0"},"titleTypography":{"type":"variable","id":"h6-font","font":{"label":"Prata","value":"Prata","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"400"},"percentColor":{"type":"variable","id":"theme-4"},"percentTypography":{"type":"variable","id":"bodytext-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10"}}},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-progress-bar guten-T9T8GR"><div class="progress-group"><div class="progress-skill-bar"><div class="skill-bar-content"><span class="skill-title">Videography</span></div><div class="skill-bar"><div class="skill-track" data-width="89" data-duration="3500"><div class="number-percentage-wrapper"><span class="number-percentage loaded"></span></div></div></div></div></div></div>
<!-- /wp:gutenverse/progress-bar --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
